# Numpy

Numpy è un modulo che gestisce e manipola array di numeri.

Permette di svolgere operazioni tra tutti gli elementi con una sola istruzione facendo risparmiare molte linee di codice. In questo modo lo stile del codice eviterà diversi *loop* uno dentro l'altro favorendo una scrittura più lineare ed in genere fornisce implementazioni più veloci.

A differenze delle liste python, **il tipo di dati è fisso** in numpy perché usa aree di memoria contigue. Questo rende l'implementazione più rapida delle liste usuali. 

* <a href="https://numpy.org/">documentazione</a>

* <a href="https://youtu.be/GB9ByFAIAH4">tutorial online</a>

In [60]:
import numpy as np
import math
import time

In [2]:
x = [2, 5, 6]
y = [3, 7, 8, 10]
xy = x+y
xy

[2, 5, 6, 3, 7, 8, 10]

In [3]:
x = np.array([2, 5, 6])
y = np.array([3, 7, 8])
xy = x+y
print(xy)

[ 5 12 14]


Definiamo una matrice di rotazione di un angolo $\theta = \pi/3$:

In [4]:
theta = math.pi/3
st = math.sin(theta); ct = math.cos(theta)
rot = np.array(((ct, st),
                (-st, ct)))
print(rot)
print("dimensions: ", rot.ndim)
print("rows, cols: ", rot.shape)
print("data type: ", rot.dtype)

[[ 0.5        0.8660254]
 [-0.8660254  0.5      ]]
dimensions:  2
rows, cols:  (2, 2)
data type:  float64


In [5]:
rot11 = rot[0,0]; rot12 = rot[0,1]
rot21 = rot[1,0]; rot22 = rot[1,1]
print(rot11, rot12)
print(rot21, rot22)

0.5000000000000001 0.8660254037844386
-0.8660254037844386 0.5000000000000001


Il tipo dei dati può essere specificato come parametro al momento della creazione dell'array.

In [6]:
x = np.array([2, 5, 6], np.int32)
print(x)

[2 5 6]


In [7]:
x = np.array([2, 5, 6], np.float16)
print(x)

[2. 5. 6.]


Accesso alle specifiche righe:

In [8]:
print(rot[0])
print(rot[1])
print(rot[0, :])
print(rot[1, :])

[0.5       0.8660254]
[-0.8660254  0.5      ]
[0.5       0.8660254]
[-0.8660254  0.5      ]


Accesso alle specifiche colonne:

In [9]:
print(rot[:, 0])
print(rot[:, 1])

[ 0.5       -0.8660254]
[0.8660254 0.5      ]


Accesso a sottoinsiemi della matrice (ossia al *minore* della matrice).
Notare: l'ultimo indice in ```1:3``` non è incluso!

In [10]:
m = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10 , 11, 12]])
print(m)
m1 = m[1:3, 1:3]
print(m1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 6  7]
 [10 11]]


Accesso agli elementi saltandone un certo numero

In [11]:
m = np.array([[1, 2, 3, 4, 5, 6, 7, 8],
              [9, 10 , 11, 12, 13, 14, 15, 16]])
print(m)
# skip even or odd columns 
me = m[:, 0:8:2]
mo = m[:, 1:8:2]
print(me)
print(mo)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
[[ 1  3  5  7]
 [ 9 11 13 15]]
[[ 2  4  6  8]
 [10 12 14 16]]


Accesso ad elementi dato un insieme di indici

Accesso a sottoinsiemi in scrittura:

In [12]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [13]:
x[2:5] = 2
print(x)

[0. 0. 2. 2. 2. 0. 0. 0. 0. 0.]


In [14]:
x[2:5] = [1, 2, 3]
print(x)

[0. 0. 1. 2. 3. 0. 0. 0. 0. 0.]


Inizializzazione: tutti zeri o uno, o non inizializzati

In [15]:
x = np.ones((3,2))
print(x)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [16]:
x = np.zeros((3,2))
print(x)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [17]:
x = np.empty((6,8))
print(x)

[[ 4.63985646e-310  0.00000000e+000  6.94261466e-310  6.94261464e-310
   6.94261426e-310  6.94261468e-310  6.94261426e-310  6.94261426e-310]
 [ 6.94261520e-310  6.94261416e-310  6.94261413e-310  6.94261415e-310
   6.94261506e-310  6.94261524e-310  6.94261456e-310  6.94261416e-310]
 [ 6.94261415e-310  6.94261408e-310  6.94261416e-310  6.94261408e-310
   6.94261507e-310  6.94261408e-310  6.94261413e-310  6.94261518e-310]
 [ 6.94261437e-310  6.94261515e-310  6.94261522e-310  6.94261516e-310
   6.94261524e-310  6.94261467e-310  6.94261522e-310  6.94261521e-310]
 [ 6.94261412e-310  6.94261514e-310  6.94261416e-310  6.94261416e-310
   0.00000000e+000  4.79243676e-322  4.63985656e-310  6.94261556e-310]
 [ 3.18978592e+164  0.00000000e+000  0.00000000e+000 -2.77644455e-240
   6.94261426e-310  6.94261426e-310  4.52965101e+094  6.94261410e-310]]


Inizializzazione: tutti valori uguali

In [18]:
x = np.full((2,3),3.14)
print(x)

[[3.14 3.14 3.14]
 [3.14 3.14 3.14]]


Inizializzazione: casuale

In [19]:
r = np.random.rand(3,3)
print(r)

[[0.5939551  0.82349055 0.66067726]
 [0.7134982  0.02286838 0.38054285]
 [0.6216963  0.21470452 0.86801161]]


Matrice identità

In [20]:
i = np.identity(4)
print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Accesso a blocchi in scrittura

In [21]:
i[2:4,0:2] = rot
print(i)

[[ 1.         0.         0.         0.       ]
 [ 0.         1.         0.         0.       ]
 [ 0.5        0.8660254  1.         0.       ]
 [-0.8660254  0.5        0.         1.       ]]


In [22]:
i[0:2,2:4] = rot
print(i)

[[ 1.         0.         0.5        0.8660254]
 [ 0.         1.        -0.8660254  0.5      ]
 [ 0.5        0.8660254  1.         0.       ]
 [-0.8660254  0.5        0.         1.       ]]


Selezione di elementi multipli in base ad un insieme di indici:

In [23]:
x = np.array([10, 20, 30, 40, 50, 60, 70, 80])
ev = x[[1, 3, 5, 7]]
od = x[[0, 2, 4, 6]]
print(ev)
print(od)

[20 40 60 80]
[10 30 50 70]


In [24]:
x = np.array([[0, 10, 20, 30, 40, 50, 60]])
np.take(x, [2, 3, 5])

array([20, 30, 50])

In [25]:
m = np.array([[1, 0, 0, 0],
              [0, 2, 0, 0],
              [0, 0, 3, 0],
              [0, 0, 0, 4]])
print(m)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [26]:
diag = m[[0, 1, 2, 3], [0, 1, 2, 3]]
print(diag)

[1 2 3 4]


# Copie: shallow vs deep
La copia di default è *shallow*, ossia viene assegnato un puntatore all'oggetto originale. Per avere una copia diversa dall'ogetto originale bisogna usare il metodo ```copy()```.

In [27]:
a = np.zeros(5)
b = a
print(a, b)

[0. 0. 0. 0. 0.] [0. 0. 0. 0. 0.]


In [28]:
a[2] = 9
b[3] = 2
print(a,b)

[0. 0. 9. 2. 0.] [0. 0. 9. 2. 0.]


In [29]:
a = np.zeros(5)
b = a.copy()
print(a, b)
a[2] = 9
b[3] = 2
print(a,b)

[0. 0. 0. 0. 0.] [0. 0. 0. 0. 0.]
[0. 0. 9. 0. 0.] [0. 0. 0. 2. 0.]


# Manipolazione con operazioni matematiche

In sostanza, tutte le operazioni vengono svolte elemento per elemento.

Attenzione! La moltiplicazione tra matrici su puà fare come ```np.matmul(a,b)```, **non** come ```a*b```.

In [30]:
a = np.array([1, 2, 3])
b = a*2
print(a, b)

[1 2 3] [2 4 6]


Moltiplicazione elemento per elento

In [31]:
a = np.array([1, 2, 3, 4]); b = np.array([3, 4, 5, 6])
ab = a*b
print(a, b, ab)

[1 2 3 4] [3 4 5 6] [ 3  8 15 24]


In [32]:
a6 = a**6
print(a, a6)

[1 2 3 4] [   1   64  729 4096]


Sequenza equispaziata tra un valore minimo ed un valore massimo

In [33]:
bins = 10
theta = np.linspace(0, math.pi, bins)
print(theta)

[0.         0.34906585 0.6981317  1.04719755 1.3962634  1.74532925
 2.0943951  2.44346095 2.7925268  3.14159265]


In [34]:
theta = np.linspace(0, math.pi, 12)
print(theta)

[0.         0.28559933 0.57119866 0.856798   1.14239733 1.42799666
 1.71359599 1.99919533 2.28479466 2.57039399 2.85599332 3.14159265]


Possiamo calcolare i valori di una funzione corrispondenti agli elementi che passiamo.

Questa funzione è estremamente utile per fare grafici di una funzione, che di fatto sono curve che passano per una serie di punti forniti dall'utente.

In [35]:
ct = np.cos(theta)
st = np.sin(theta)
np.set_printoptions(precision=4, suppress=True)
print(ct)
print(st)

[ 1.      0.9595  0.8413  0.6549  0.4154  0.1423 -0.1423 -0.4154 -0.6549
 -0.8413 -0.9595 -1.    ]
[0.     0.2817 0.5406 0.7557 0.9096 0.9898 0.9898 0.9096 0.7557 0.5406
 0.2817 0.    ]


Applicare ripetutamente una funzione. Questa possibilità sfrutta il fatto che python è un interprete. Purché sia definito l'operatore ```**``` (```x**2```), la funzione ```fun``` può essere eseguita.

In [36]:
v = np.array([1, 2, 3, 4, 5])
fun = lambda x: x**2 - 1
#def fun(x): return x**2 -1
f = fun(v)
print(f)

[ 0  3  8 15 24]


Si può definire una funzione che prende come argomento un ```np.array``` e applica ripetutamente un'altra funzione data a ciascun elemento.

In [37]:
def sinus(x):
    return math.sin(x)+math.cos(x)

In [58]:
%%script python --no-raise-error
# l'istruzione che segue dà un errore
sinus_theta = sinus(theta)

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
NameError: name 'sinus' is not defined


In [82]:
t0 = time.time()
vfunc = np.vectorize(sinus)
sinus_theta = vfunc(theta)
print(sinus_theta)
print("time: ", time.time()-t0)

[ 1.      1.2412  1.3819  1.4106  1.325   1.1321  0.8475  0.4942  0.1009
 -0.3006 -0.6778 -1.    ]
time:  0.0017850399017333984


In [80]:
def vsinus(x):
    return np.sin(x)+np.cos(x)
t0 = time.time()
sinus_theta = vsinus(theta)
print(sinus_theta)
print("time: ", time.time()-t0)

[ 1.      1.2412  1.3819  1.4106  1.325   1.1321  0.8475  0.4942  0.1009
 -0.3006 -0.6778 -1.    ]
time:  0.0008838176727294922


In [83]:
v = np.array([0.0, 0.1, 0.2, 0.3])
fun = lambda x: 1.0 if x==0 else math.sin(x)/x
f = np.vectorize(fun)(v)
print(f)

[1.     0.9983 0.9933 0.9851]


# Algebra lineare

Prodotto tra matrici

In [96]:
a = np.array([[1, 2, 3],
              [4, 5, 6]], np.int16)
b = np.array([[1, 2],
              [3, 4],
              [5,6]], np.int16)
ab = np.matmul(a, b)
print(ab)

[[22 28]
 [49 64]]


Determinante.
**Attenzione! Utilizza solo il formato floating point.**

In [95]:
det = np.linalg.det(ab)
print(det)
print(22*64 - 28*49)

35.99999999999982
36


Matrice inversa

In [88]:
inv = np.linalg.inv(ab)
print(inv)

[[ 1.7778 -0.7778]
 [-1.3611  0.6111]]


Calcolo degli autovalori ed autovettori

In [97]:
a = np.array([[1, 2, 0, 0],
              [2, 1, 0, 0],
              [0, 0, 2, 3],
              [0, 0, 3, 2]])
print(a)

[[1 2 0 0]
 [2 1 0 0]
 [0 0 2 3]
 [0 0 3 2]]


In [98]:
w, v = np.linalg.eig(a)
print(w)
print(v)

[ 3. -1.  5. -1.]
[[ 0.7071 -0.7071  0.      0.    ]
 [ 0.7071  0.7071  0.      0.    ]
 [ 0.      0.      0.7071 -0.7071]
 [ 0.      0.      0.7071  0.7071]]


# Principali indicatori statistici

In seguito daremo una più precisa definizione degli indicatori statistici. Quella che segue è solo un'anteprima.

In [106]:
x = np.random.rand(10)
print(x)
print(x.min(),x.max())
print("sum: ", x.sum())
print("mean: ", x.sum()/x.shape[0])
print("mean: ", x.mean())
print("mean sq: ", (x**2).mean())
print("variance: ", (x**2).mean()-x.mean()**2)
print("variance: ", x.var())
print("std. dev: ", math.sqrt(x.var()))
print("std. dev: ", x.std())

[0.2941 0.8155 0.6743 0.1234 0.4254 0.3855 0.9464 0.2973 0.5156 0.1326]
0.12342097144015429 0.9463518052756769
sum:  4.610105963396513
mean:  0.46101059633965125
mean:  0.46101059633965125
mean sq:  0.2818487393755318
variance:  0.06931796943809093
variance:  0.0693179694380909
std. dev:  0.26328305953496306
std. dev:  0.26328305953496306


In [107]:
m = np.random.rand(6, 4)
print(m)
print("sum: ", m.sum())
print("sum cols: ", m.sum(axis = 0))
print("sum rows: ", m.sum(axis = 1))

[[0.3146 0.5592 0.6132 0.9769]
 [0.5885 0.4646 0.214  0.969 ]
 [0.9304 0.1213 0.2012 0.1621]
 [0.8829 0.7151 0.8154 0.5325]
 [0.352  0.0122 0.5772 0.4472]
 [0.6391 0.6568 0.027  0.0206]]
sum:  11.792899846050602
sum cols:  [3.7076 2.5292 2.448  3.1082]
sum rows:  [2.4638 2.2361 1.415  2.9459 1.3886 1.3435]


# Altre manipolazioni

In [109]:
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])
v = np.vstack([v1,v2])
print(v)

[[1 2 3 4]
 [5 6 7 8]]


In [110]:
h1 = np.array([[1, 2], [3, 4]])
h2 = np.array([[5, 6, 7], [8, 9, 10]])
h = np.hstack([h1, h2])
print(h)

[[ 1  2  5  6  7]
 [ 3  4  8  9 10]]


Non è una funzione ```numpy```, ma è un modo comodo per iterare contemporaneamente su due o più array:

In [ ]:
v = zip(v1, v2)
print(v)
for a, b in zip(v1, v2):
    print(a, b)

Alternativa in programmazione più "classica":

In [113]:
for i in range(len(v1)):
    print(v1[i], v2[i])

1 5
2 6
3 7
4 8


# Input da file
I numeri sono di default interpretati come float

In [116]:
m = np.genfromtxt('data/np-data.txt', delimiter=',')
print(m)

[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]


In [ ]:
m = m.astype('int32')
print(m)

In [122]:
m = np.genfromtxt('data/np-data.txt', delimiter=',', dtype=np.int8)
print(m)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Condizioni booleane

In [129]:
m > 3

array([[False, False],
       [False,  True],
       [ True,  True],
       [ True,  True]])

In [130]:
m < 7

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [False, False]])

In [134]:
(m > 3) & (m < 7)

array([[False, False],
       [False,  True],
       [ True,  True],
       [False, False]])

Selezione degli elementi secondo una condizione

In [135]:
x = np.random.rand(10)
print(x)

[0.4534 0.964  0.5679 0.2655 0.1056 0.966  0.9967 0.7227 0.5789 0.9735]


In [137]:
print(x > 0.5)

[False  True  True False False  True  True  True  True  True]


In [136]:
x1 = x[x > 0.5]
print(x1)

[False  True  True False False  True  True  True  True  True]
[0.964  0.5679 0.966  0.9967 0.7227 0.5789 0.9735]
